import re
email='''1	eric.lopez@gmail.com
2	eric.lund@gmail.com
3	eric.m.boehm@gmail.com
4	eric.mack@gmail.com
5	eric.mason@gmail.com
6	eric.mathews@gmail.com
7	eric.maynard@gmail.com
8	eric.mckinney@gmail.com
9	eric.meredith@gmail.com
10	eric.mintz@gmail.com
11	eric.mistry@gmail.com
12	eric.mittler@gmail.com
13	eric.moeller@gmail.com
14	eric.monica@gmail.com
15	eric.moore@gmail.com
16	eric.murrell@gmail.com
17	eric.nay@gmail.com
18	eric.neilson@gmail.com
19	eric.nelson@gmail.com
20	eric.newcomer@gmail.com
21	eric.nghiem@gmail.com
22	eric.nishant@gmail.com
23	eric.noss@gmail.com
24	eric.nyberg@gmail.com
25	eric.o.neil@gmail.com
26	eric.odonnell@gmail.com
27	eric.ogren@gmail.com
28	eric.olsen@gmail.com
29	eric.oosterhof@gmail.com
30	eric.pace@gmail.com
31	eric.pam@gmail.com
32	eric.parker@gmail.com
33	eric.pc@gmail.com
34	eric.pedersen@gmail.com
35	eric.perry@gmail.com
36	eric.poole@gmail.com
37	eric.prathap@gmail.com
38	eric.price@gmail.com
39	eric.raber@gmail.com
40	eric.reidmiller@gmail.com
41	eric.rhinehart@gmail.com
42	eric.richie@gmail.com
43	eric.roberts@gmail.com
44	eric.roger@gmail.com
45	eric.ruby@gmail.com
46	eric.ruck@gmail.com
47	eric.rud@gmail.com
48	eric.salman@gmail.com
49	eric.santelices@gmail.com
50	eric.sayer@gmail.com
51	eric.scarbrough@gmail.com
52	eric.schaefer@gmail.com
53	eric.schmidt@gmail.com
54	eric.schuller@gmail.com
55	eric.shapiro@gmail.com
56	eric.sheppard@gmail.com
57	eric.sherman@gmail.com
58	eric.shirley@gmail.com
59	eric.simmons@gmail.com
60	eric.simons@gmail.com
61	eric.sineath@gmail.com
62	eric.smith@gmail.com
63	eric.smtih@gmail.com
64	eric.speicher@gmail.com
65	eric.staley@gmail.com
66	eric.stephan@gmail.com
67	eric.stephenson@gmail.com
68	eric.sudan@gmail.com
69	eric.summers@gmail.com
70	eric.sumpter@gmail.com
71	eric.sun@gmail.com
72	eric.sylvers@gmail.com
73	eric.tam@gmail.com
74	eric.taylor@gmail.com
75	eric.therrien@gmail.com
76	eric.thompson@gmail.com
77	eric.troup@gmail.com
78	eric.truong@gmail.com
79	eric.urban@gmail.com
80	eric.vann@gmail.com
81	eric.vice@gmail.com
82	eric.vlasic@gmail.com
83	eric.vyncke@gmail.com
84	eric.waggott@gmail.com
85	eric.walker@gmail.com
86	eric.wang@gmail.com
87	eric.warren@gmail.com
88	eric.weaver@gmail.com
89	eric.weber@gmail.com
90	eric.weeks@gmail.com
'''


pattern=re.compile(r'\w+[.]\w+[@]\w+[.]\w+')
matches=pattern.finditer(email)
for match in matches:
    print(match)

